#!/usr/bin/env bash
# bashqueues QueueManager
#
# Sourced lazily by queuebash.sh. Keeps menu/UI routing out of the core engine.
#
# Design rules:
#   - Do not mutate core queue state directly where a queue command exists.
#   - Generate record-format classes only.
#   - Keep all commands scriptable as well as menu-driven.

_queue_mgr_pause() {
    [[ "${QUEUEBASH_ALLOW_NONINTERACTIVE:-0}" == "1" ]] && return 0
    echo
    read -r -p "Press Enter to continue..." _
}

_queue_mgr_header() {
    local title="$1"
    clear 2>/dev/null || true
    echo "=============================================================================="
    echo "QUEUEBASH MANAGER - $title"
    echo "=============================================================================="
}

_queue_mgr_prompt() {
    local prompt="$1"
    local default="${2:-}"
    local value

    if [[ -n "$default" ]]; then
        read -r -p "$prompt [$default]: " value
        printf '%s\n' "${value:-$default}"
    else
        read -r -p "$prompt: " value
        printf '%s\n' "$value"
    fi
}

_queue_mgr_yesno() {
    local prompt="$1"
    local default="${2:-N}"
    local ans

    read -r -p "$prompt [$default]: " ans
    ans="${ans:-$default}"
    case "${ans,,}" in
        y|yes|1|true) return 0 ;;
        *) return 1 ;;
    esac
}

_queue_mgr_require_class_name() {
    local class="$1"
    if [[ -z "$class" ]]; then
        echo "QueueManager: class name required" >&2
        return 2
    fi
    if [[ ! "$class" =~ ^[A-Za-z_][A-Za-z0-9_-]*$ ]]; then
        echo "QueueManager: invalid class name: $class" >&2
        return 2
    fi
}

_queue_mgr_quote() {
    # Print a Bash-safe representation of one argument.
    printf '%q' "$1"
}


_queue_mgr_asset_hint() {
    local facility="$1"
    local out rc

    if [[ -z "$facility" ]]; then
        echo "Usage: queue mgr hint <family:facility>"
        return 2
    fi

    out="$(queue asset-hint "$facility" 2>/dev/null)"
    rc="$?"

    if [[ "$rc" -eq 0 ]]; then
        printf '%s\n' "$out"
        return 0
    fi

    echo "No published helper hint for: $facility"
    echo
    echo "Use:"
    echo "  queue assets explain $facility"
    echo
    echo "Generic record format:"
    echo "  queue_class_shared_asset FAMILY CHECK \"TARGET\" key=value"
    echo "  queue_class_exclusive_asset FAMILY CHECK \"TARGET\" key=value"
}

_queue_mgr_asset_hints_list() {
    echo "Published helper hints:"
    queue asset-hints 2>/dev/null || true
}

_queue_mgr_facility_picker() {
    echo
    echo "Installed asset facilities:"
    echo "------------------------------------------------------------------------------"
    queue assets 2>/dev/null || true
    echo "------------------------------------------------------------------------------"
    echo
    echo "Published helper hints:"
    _queue_mgr_asset_hints_list | sed 's/^/  /'
    echo
}

_queue_mgr_write_class_file() {
    local class="$1"
    local allow_parallel="$2"
    local max_concurrent="$3"
    local outfile="$4"
    shift 4
    local line

    {
        echo "# bashqueues class: $class"
        echo "# Generated by QueueManager on $(date -Is 2>/dev/null || date)"
        echo
        echo "CLASS_ALLOW_PARALLEL=$allow_parallel"
        echo "CLASS_MAX_CONCURRENT=$max_concurrent"
        echo
        echo "# Record-format assets only."
        echo "#   queue_class_shared_asset family check \"target\" key=value"
        echo "#   queue_class_exclusive_asset family check \"target\" key=value"
        echo "#   queue_class_exclusive_claim \"claim-token\""
        echo

        for line in "$@"; do
            [[ -n "$line" ]] && printf '%s\n' "$line"
        done
    } > "$outfile"
}

_queue_mgr_class_create_noninteractive() {
    local class="$1"
    shift || true

    _queue_mgr_require_class_name "$class" || return "$?"

    local allow_parallel=1
    local max_concurrent=0
    local -a records=()
    local -a default_lines=()
    local family check target mode claim
    local tmp root

    while [[ "$#" -gt 0 ]]; do
        case "$1" in
            --parallel)
                allow_parallel=1
                shift
                ;;
            --no-parallel|--sequential)
                allow_parallel=0
                [[ "$max_concurrent" == "0" ]] && max_concurrent=1
                shift
                ;;
            --max-concurrent)
                [[ $# -ge 2 ]] || { echo "QueueManager: --max-concurrent needs a value" >&2; return 2; }
                max_concurrent="$2"
                [[ "$max_concurrent" =~ ^[0-9]+$ ]] || { echo "QueueManager: max concurrent must be numeric" >&2; return 2; }
                shift 2
                ;;
            --default-runner)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-runner needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_RUNNER=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-cpu-limit)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-cpu-limit needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_CPU_LIMIT=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-mem-limit)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-mem-limit needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_MEM_LIMIT=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-max-log-size)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-max-log-size needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_MAX_LOG_SIZE_BYTES=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-log-policy)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-log-policy needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_LOG_OVERFLOW_POLICY=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-allow-large-log)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-allow-large-log needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_ALLOW_LARGE_LOG=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-timeout)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-timeout needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_TIMEOUT=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-kill-after)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-kill-after needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_KILL_AFTER=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-log-tag)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-log-tag needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_LOG_TAG=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-output-dir)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-output-dir needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_OUTPUT_DIR=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-env-prefix)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-env-prefix needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_ENV_PREFIX=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-cpu-seconds)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-cpu-seconds needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_CPU_SECONDS=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-wall-seconds)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-wall-seconds needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_WALL_SECONDS=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-billing-cycles)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-billing-cycles needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_BILLING_CYCLES=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-billing-unit-seconds)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-billing-unit-seconds needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_BILLING_UNIT_SECONDS=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-billing-grace-seconds)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-billing-grace-seconds needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_BILLING_GRACE_SECONDS=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-billing-policy)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-billing-policy needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_BILLING_POLICY=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --default-working-dir)
                [[ $# -ge 2 ]] || { echo "QueueManager: --default-working-dir needs a value" >&2; return 2; }
                default_lines+=("CLASS_DEFAULT_WORKING_DIR=$(_queue_mgr_quote "$2")")
                shift 2
                ;;
            --exclusive-claim)
                [[ $# -ge 2 ]] || { echo "QueueManager: --exclusive-claim needs a token" >&2; return 2; }
                claim="$2"
                records+=("queue_class_exclusive_claim $(_queue_mgr_quote "$claim")")
                shift 2
                ;;
            --shared-asset|--exclusive-asset)
                mode="$1"
                [[ $# -ge 4 ]] || { echo "QueueManager: $mode requires family check target [params...]" >&2; return 2; }
                family="$2"
                check="$3"
                target="$4"
                shift 4

                local -a params=()
                while [[ "$#" -gt 0 ]]; do
                    case "$1" in
                        --shared-asset|--exclusive-asset|--exclusive-claim|--max-concurrent|--parallel|--no-parallel|--sequential|--replace|--force)
                            break
                            ;;
                        *)
                            params+=("$1")
                            shift
                            ;;
                    esac
                done

                local cmd
                if [[ "$mode" == "--shared-asset" ]]; then
                    cmd="queue_class_shared_asset"
                else
                    cmd="queue_class_exclusive_asset"
                fi

                local rec="$cmd $(_queue_mgr_quote "$family") $(_queue_mgr_quote "$check") $(_queue_mgr_quote "$target")"
                local p
                for p in "${params[@]}"; do
                    rec+=" $(_queue_mgr_quote "$p")"
                done
                records+=("$rec")
                ;;
            --replace|--force)
                # Accepted for readability. queue classes replace is inherently replace-with-backup.
                shift
                ;;
            *)
                echo "QueueManager: unknown class-create option: $1" >&2
                return 2
                ;;
        esac
    done

    root="$(_queue_root)"
    mkdir -p "$root/classes"

    tmp="$(mktemp)"
    _queue_mgr_write_class_file "$class" "$allow_parallel" "$max_concurrent" "$tmp" "${default_lines[@]}" "${records[@]}"

    queue classes replace "$class" "$tmp"
    local rc="$?"
    rm -f "$tmp"
    return "$rc"
}

_queue_mgr_class_create_interactive() {
    local class="${1:-}"
    local allow_parallel max_concurrent tmp root
    local -a records=()
    local -a default_lines=()

    _queue_mgr_header "CLASS CREATE"

    if [[ -z "$class" ]]; then
        class="$(_queue_mgr_prompt "Class name")"
    fi
    _queue_mgr_require_class_name "$class" || return "$?"

    if _queue_mgr_yesno "Allow parallel jobs for this class?" "Y"; then
        allow_parallel=1
        max_concurrent="$(_queue_mgr_prompt "Max concurrent, 0 for unlimited" "0")"
    else
        allow_parallel=0
        max_concurrent="$(_queue_mgr_prompt "Max concurrent" "1")"
    fi

    echo
    echo "Configure class default job settings. Blank keeps unset."
    local v
    v="$(_queue_mgr_prompt "Default runner (auto/systemd/direct)")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_RUNNER=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default CPU limit, e.g. 50%")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_CPU_LIMIT=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default memory limit, e.g. 512M")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_MEM_LIMIT=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default max log bytes")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_MAX_LOG_SIZE_BYTES=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default log overflow policy")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_LOG_OVERFLOW_POLICY=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default timeout, e.g. 30s")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_TIMEOUT=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default kill-after, e.g. 5s")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_KILL_AFTER=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default log tag template" '${JOB_NAME}.${JOB_ID}')"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_LOG_TAG=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default output dir template" '${QUEUEBASH_ROOT}/class_outputs/${JOB_NAME}/${JOB_ID}')"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_OUTPUT_DIR=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default env prefix template" '${JOB_NAME}_${JOB_ID}')"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_ENV_PREFIX=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default working directory")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_WORKING_DIR=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default CPU seconds cap")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_CPU_SECONDS=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default wall seconds cap")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_WALL_SECONDS=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default billing cycles")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_BILLING_CYCLES=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default billing unit seconds, e.g. 60")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_BILLING_UNIT_SECONDS=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default billing grace seconds, e.g. 5")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_BILLING_GRACE_SECONDS=$(_queue_mgr_quote "$v")")
    v="$(_queue_mgr_prompt "Default billing policy" "shortest-cap-wins")"; [[ -n "$v" ]] && default_lines+=("CLASS_DEFAULT_BILLING_POLICY=$(_queue_mgr_quote "$v")")

    echo
    echo "Add exclusive class-level claim tokens, one per line. Blank line ends."
    while true; do
        local claim
        claim="$(_queue_mgr_prompt "Exclusive claim")"
        [[ -z "$claim" ]] && break
        records+=("queue_class_exclusive_claim $(_queue_mgr_quote "$claim")")
    done

    echo
    echo "Add asset checks. Blank family ends."
    echo "Type '?' as the family to list assets/hints."
    while true; do
        local family check target access params rec cmd facility
        family="$(_queue_mgr_prompt "Asset family")"
        [[ -z "$family" ]] && break
        if [[ "$family" == "?" ]]; then
            _queue_mgr_facility_picker
            continue
        fi
        check="$(_queue_mgr_prompt "Facility/check")"
        facility="$family:$check"
        echo
        _queue_mgr_asset_hint "$facility"
        echo
        target="$(_queue_mgr_prompt "Target")"
        access="$(_queue_mgr_prompt "Access shared/exclusive" "shared")"
        params="$(_queue_mgr_prompt "Parameters as key=value words, blank for none")"

        if [[ "${access,,}" == e* ]]; then
            cmd="queue_class_exclusive_asset"
        else
            cmd="queue_class_shared_asset"
        fi

        rec="$cmd $(_queue_mgr_quote "$family") $(_queue_mgr_quote "$check") $(_queue_mgr_quote "$target")"
        if [[ -n "$params" ]]; then
            # Deliberately shell-tokenised here because the user entered a key=value word list.
            # For values containing spaces, use non-interactive class-create.
            local p
            for p in $params; do
                rec+=" $(_queue_mgr_quote "$p")"
            done
        fi
        records+=("$rec")
    done

    root="$(_queue_root)"
    mkdir -p "$root/classes"
    tmp="$(mktemp)"
    _queue_mgr_write_class_file "$class" "$allow_parallel" "$max_concurrent" "$tmp" "${default_lines[@]}" "${records[@]}"

    echo
    echo "Generated class file:"
    echo "------------------------------------------------------------------------------"
    cat "$tmp"
    echo "------------------------------------------------------------------------------"
    echo

    if _queue_mgr_yesno "Save this class?" "Y"; then
        queue classes replace "$class" "$tmp"
    else
        echo "Class not saved."
    fi

    rm -f "$tmp"
}

_queue_mgr_classes_menu() {
    while true; do
        _queue_mgr_header "CLASSES"
        echo "1. List classes"
        echo "2. Show class"
        echo "3. Explain class"
        echo "4. Create class"
        echo "5. Class wizard"
        echo "6. Edit class"
        echo "7. Validate classes"
        echo "8. Refresh classes from directory"
        echo "9. Delete/archive class"
        echo "10. Undelete class"
        echo "11. Back"
        echo
        read -r -p "Selection: " sel

        case "$sel" in
            1) queue classes list; _queue_mgr_pause ;;
            2) c="$(_queue_mgr_prompt "Class")"; queue classes show "$c"; _queue_mgr_pause ;;
            3) c="$(_queue_mgr_prompt "Class")"; queue classes explain "$c"; _queue_mgr_pause ;;
            4) c="$(_queue_mgr_prompt "Class")"; _queue_mgr_class_create_interactive "$c"; _queue_mgr_pause ;;
            5) c="$(_queue_mgr_prompt "Class")"; _queue_mgr_class_wizard "$c"; _queue_mgr_pause ;;
            6) c="$(_queue_mgr_prompt "Class")"; queue classes edit "$c"; _queue_mgr_pause ;;
            7) queue classes validate; _queue_mgr_pause ;;
            8) d="$(_queue_mgr_prompt "Directory")"; queue classes refresh "$d"; _queue_mgr_pause ;;
            9) c="$(_queue_mgr_prompt "Class")"; queue classes delete "$c"; _queue_mgr_pause ;;
            10) c="$(_queue_mgr_prompt "Class")"; queue classes undelete "$c"; _queue_mgr_pause ;;
            11|q|Q) return 0 ;;
        esac
    done
}

_queue_mgr_assets_menu() {
    while true; do
        _queue_mgr_header "ASSETS"
        echo "1. List asset facilities"
        echo "2. Explain facility"
        echo "3. Hint for facility"
        echo "4. List built-in hints"
        echo "5. Validate plugins"
        echo "6. Refresh plugins from directory"
        echo "7. Replace plugin"
        echo "8. Rollback plugin"
        echo "9. Delete/archive plugin"
        echo "10. Undelete plugin"
        echo "11. Back"
        echo
        read -r -p "Selection: " sel

        case "$sel" in
            1) queue assets; _queue_mgr_pause ;;
            2) f="$(_queue_mgr_prompt "Facility, e.g. net:http_status")"; queue assets explain "$f"; _queue_mgr_pause ;;
            3) f="$(_queue_mgr_prompt "Facility, e.g. net:http_status")"; _queue_mgr_asset_hint "$f"; _queue_mgr_pause ;;
            4) _queue_mgr_asset_hints_list; _queue_mgr_pause ;;
            5) queue assets validate; _queue_mgr_pause ;;
            6) d="$(_queue_mgr_prompt "Directory")"; queue asset-refresh "$d"; _queue_mgr_pause ;;
            7) fam="$(_queue_mgr_prompt "Family")"; file="$(_queue_mgr_prompt "Plugin file")"; queue assets replace "$fam" "$file"; _queue_mgr_pause ;;
            8) fam="$(_queue_mgr_prompt "Family")"; queue assets rollback "$fam"; _queue_mgr_pause ;;
            9) fam="$(_queue_mgr_prompt "Family")"; queue assets delete "$fam"; _queue_mgr_pause ;;
            10) fam="$(_queue_mgr_prompt "Family")"; queue assets undelete "$fam"; _queue_mgr_pause ;;
            11|q|Q) return 0 ;;
        esac
    done
}

_queue_mgr_jobs_menu() {
    while true; do
        _queue_mgr_header "JOBS"
        echo "1. List jobs"
        echo "2. Show job"
        echo "3. Explain job"
        echo "4. Tail job"
        echo "5. Cancel job"
        echo "6. Run queue"
        echo "7. Back"
        echo
        read -r -p "Selection: " sel

        case "$sel" in
            1) queue list; _queue_mgr_pause ;;
            2) j="$(_queue_mgr_prompt "Job id/name")"; queue show "$j"; _queue_mgr_pause ;;
            3) j="$(_queue_mgr_prompt "Job id/name")"; queue explain "$j"; _queue_mgr_pause ;;
            4) j="$(_queue_mgr_prompt "Job id/name")"; queue tail "$j"; _queue_mgr_pause ;;
            5) j="$(_queue_mgr_prompt "Job id/name")"; queue cancel "$j"; _queue_mgr_pause ;;
            6) queue run; _queue_mgr_pause ;;
            7|q|Q) return 0 ;;
        esac
    done
}

_queue_mgr_workers_menu() {
    while true; do
        _queue_mgr_header "WORKERS"
        echo "1. Show workers"
        echo "2. Start workers"
        echo "3. Health"
        echo "4. Health --fix"
        echo "5. Dispatch trace"
        echo "6. Duplicate QIDs"
        echo "7. Back"
        echo
        read -r -p "Selection: " sel

        case "$sel" in
            1) queue workers; _queue_mgr_pause ;;
            2) n="$(_queue_mgr_prompt "Worker count" "1")"; queue start --workers "$n"; _queue_mgr_pause ;;
            3) queue health; _queue_mgr_pause ;;
            4) queue health --fix; _queue_mgr_pause ;;
            5) queue dispatch-trace; _queue_mgr_pause ;;
            6) queue duplicate-qids; _queue_mgr_pause ;;
            7|q|Q) return 0 ;;
        esac
    done
}

_queue_mgr_main_menu() {
    while true; do
        _queue_mgr_header "MAIN MENU"
        echo "1. Jobs"
        echo "2. Classes"
        echo "3. Assets"
        echo "4. Workers / Health / Trace"
        echo "5. Exit"
        echo
        read -r -p "Selection: " sel

        case "$sel" in
            1) _queue_mgr_jobs_menu ;;
            2) _queue_mgr_classes_menu ;;
            3) _queue_mgr_assets_menu ;;
            4) _queue_mgr_workers_menu ;;
            5|q|Q|exit) return 0 ;;
        esac
    done
}

_queue_manager() {
    local action="${1:-menu}"
    shift || true

    case "$action" in
        menu|"")
            _queue_mgr_main_menu
            ;;
        jobs)
            _queue_mgr_jobs_menu "$@"
            ;;
        classes|class)
            _queue_mgr_classes_menu "$@"
            ;;
        assets|asset)
            _queue_mgr_assets_menu "$@"
            ;;
        workers|health)
            _queue_mgr_workers_menu "$@"
            ;;
        panel|full|fullscreen|screen)
            _queue_mgr_panel
            ;;
        class-create|create-class)
            local class="${1:-}"
            [[ $# -gt 0 ]] && shift
            _queue_mgr_class_create_noninteractive "$class" "$@"
            ;;
        class-create-interactive|create-class-interactive)
            _queue_mgr_class_create_interactive "${1:-}"
            ;;
        asset-refresh|refresh-assets)
            queue asset-refresh "${1:-}"
            ;;
        class-refresh|refresh-classes)
            queue class-refresh "${1:-}"
            ;;
        hint|asset-hint)
            _queue_mgr_asset_hint "${1:-}"
            ;;
        hints|asset-hints)
            _queue_mgr_asset_hints_list
            ;;
        picker|asset-picker)
            _queue_mgr_facility_picker
            ;;
        help|-h|--help)
            cat <<'EOF'
QueueManager commands:

  queue mgr
  queue manager
  queue qm

Panel manager:
  queue mgr panel
  queue panel

Interactive menus:
  queue mgr jobs
  queue mgr classes
  queue mgr assets
  queue mgr workers

Asset hints:
  queue mgr hints
  queue mgr hint net:http_status
  queue mgr picker

Asset refresh:
  queue assets refresh ./assets.d
  queue asset-refresh ./assets.d
  queue mgr asset-refresh ./assets.d

Class refresh:
  queue classes refresh ./classes
  queue class-refresh ./classes
  queue mgr class-refresh ./classes

Scriptable class creation:
  queue mgr class-create CLASS \
    --no-parallel \
    --max-concurrent 1 \
    --default-runner systemd \
    --default-timeout 30s \
    --default-kill-after 5s \
    --default-max-log-size 1048576 \
    --exclusive-claim github_publish:slot \
    --shared-asset net http_status "https://github.com" timeout=5 \
    --shared-asset git repo_exists "/home/hc3/bashqueues" \
    --shared-asset git branch "/home/hc3/bashqueues" require_branch=main

Record-format only. Legacy CLASS_SHARED_ASSETS is never generated.
EOF
            ;;
        *)
            echo "QueueManager: unknown action: $action" >&2
            echo "Try: queue mgr help" >&2
            return 2
            ;;
    esac
}


# ---------------------------------------------------------------------------
# Class Wizard: zero-dependency curses-ish class builder
# ---------------------------------------------------------------------------

_queue_mgr_tui_available() {
    [[ -t 0 && -t 1 ]] || return 1
    command -v tput >/dev/null 2>&1 || return 1
    return 0
}

_queue_mgr_tui_read_key() {
    local k rest
    IFS= read -rsn1 k || return 1
    if [[ "$k" == $'\e' ]]; then
        IFS= read -rsn2 -t 0.05 rest || true
        k+="$rest"
    fi
    printf '%s' "$k"
}

_queue_mgr_tui_pick() {
    local title="$1"
    shift
    local -a items=("$@")
    local selected=0
    local key rows cols top max_visible i idx label

    ((${#items[@]} > 0)) || return 1

    if ! _queue_mgr_tui_available; then
        printf '%s\n' "$title" >&2
        select label in "${items[@]}"; do
            [[ -n "$label" ]] || return 1
            printf '%s\n' "$label"
            return 0
        done
    fi

    tput smcup
    tput civis
    stty -echo -icanon time 0 min 0 2>/dev/null || true
    trap 'stty sane 2>/dev/null || true; tput cnorm 2>/dev/null || true; tput rmcup 2>/dev/null || true' RETURN INT TERM

    while true; do
        rows="$(tput lines 2>/dev/null || echo 24)"
        cols="$(tput cols 2>/dev/null || echo 80)"
        max_visible=$((rows - 6))
        ((max_visible < 5)) && max_visible=5

        if (( selected >= max_visible )); then
            top=$((selected - max_visible + 1))
        else
            top=0
        fi

        tput clear
        printf '%s\n' "$title"
        printf '%*s\n' "$cols" '' | tr ' ' '-'
        printf 'Use ↑/↓, Enter to select, q to cancel.\n\n'

        for ((i=0; i<max_visible && top+i<${#items[@]}; i++)); do
            idx=$((top+i))
            label="${items[$idx]}"
            if ((idx == selected)); then
                tput rev
                printf ' > %-.*s' $((cols-4)) "$label"
                tput sgr0
                printf '\n'
            else
                printf '   %-.*s\n' $((cols-4)) "$label"
            fi
        done

        key="$(_queue_mgr_tui_read_key)"
        case "$key" in
            $'\e[A') ((selected > 0)) && selected=$((selected-1)) ;;
            $'\e[B') ((selected < ${#items[@]}-1)) && selected=$((selected+1)) ;;
            "") ;;
            q|Q)
                return 1
                ;;
            $'\n'|$'\r')
                printf '%s\n' "${items[$selected]}"
                return 0
                ;;
        esac
    done
}

_queue_mgr_hint_line_for_facility() {
    local facility="$1"
    local line

    if declare -F _queue_asset_hint_line >/dev/null 2>&1; then
        line="$(_queue_asset_hint_line "$facility" 2>/dev/null || true)"
        [[ -n "$line" ]] && { printf '%s\n' "$line"; return 0; }
    fi

    # Fallback: parse queue asset-hint output.
    line="$(queue asset-hint "$facility" 2>/dev/null | awk '
        /^Target:/ { target=$0 }
        /^Params:/ { params=$0 }
        /^Example:/ { example=$0 }
        /^Notes:/ { notes=$0 }
        END {
            if (target || params || example || notes) {
                print target "\n" params "\n" example "\n" notes
            }
        }')"
    printf '%s\n' "$line"
}

_queue_mgr_list_facilities_compact() {
    queue assets 2>/dev/null | awk '
        /^===/ { next }
        /^$/ { next }
        /^INVALID/ { next }
        /^[[:alnum:]_+-]+:[[:alnum:]_+-]+/ {
            facility=$1
            $1=""
            sub(/^[[:space:]]+/, "")
            printf "%s\t%s\n", facility, $0
        }'
}

_queue_mgr_facility_family() {
    local facility="$1"
    printf '%s\n' "${facility%%:*}"
}

_queue_mgr_facility_check() {
    local facility="$1"
    printf '%s\n' "${facility#*:}"
}

_queue_mgr_wizard_render_preview() {
    local class="$1"
    local allow_parallel="$2"
    local max_concurrent="$3"
    local tmp="$4"
    shift 4
    local -a records=("$@")

    {
        echo "# bashqueues class: $class"
        echo "# Generated by queue mgr class-wizard"
        echo
        echo "CLASS_ALLOW_PARALLEL=$allow_parallel"
        echo "CLASS_MAX_CONCURRENT=$max_concurrent"
        echo
        if [[ -s "$tmp" ]]; then
            cat "$tmp"
            echo
        fi
        printf '%s\n' "${records[@]}"
    }
}

_queue_mgr_class_wizard() {
    local class="${1:-}"
    local allow_parallel=1
    local max_concurrent=0
    local tmp
    local -a records=()
    local -a facilities=()
    local -a menu_items=()
    local choice facility desc family check target params mode record key val
    local editor

    class="${class:-$(_queue_mgr_prompt "Class name")}"
    [[ -n "$class" ]] || { echo "QueueManager: class name required" >&2; return 2; }

    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' RETURN

    while true; do
        echo
        echo "============================================================================="
        echo "CLASS WIZARD: $class"
        echo "============================================================================="
        echo "1. Set execution/concurrency defaults"
        echo "2. Add shared asset check"
        echo "3. Add exclusive asset check"
        echo "4. Add exclusive claim token"
        echo "5. Preview class"
        echo "6. Save class"
        echo "7. Cancel"
        echo
        echo "Current records: ${#records[@]}"
        choice="$(_queue_mgr_prompt "Selection")"

        case "$choice" in
            1)
                allow_parallel="$(_queue_mgr_prompt "CLASS_ALLOW_PARALLEL" "$allow_parallel")"
                max_concurrent="$(_queue_mgr_prompt "CLASS_MAX_CONCURRENT" "$max_concurrent")"

                : > "$tmp"
                echo
                echo "Class defaults. Blank leaves unset."
                val="$(_queue_mgr_prompt "Default runner, e.g. auto/systemd/direct")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_RUNNER=%q\n' "$val" >> "$tmp"
                val="$(_queue_mgr_prompt "Default working directory")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_WORKING_DIR=%q\n' "$val" >> "$tmp"
                val="$(_queue_mgr_prompt "Default CPU limit, e.g. 50%")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_CPU_LIMIT=%q\n' "$val" >> "$tmp"
                val="$(_queue_mgr_prompt "Default memory limit, e.g. 512M")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_MEM_LIMIT=%q\n' "$val" >> "$tmp"
                val="$(_queue_mgr_prompt "Default max log bytes")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_MAX_LOG_SIZE_BYTES=%q\n' "$val" >> "$tmp"
                val="$(_queue_mgr_prompt "Default timeout, e.g. 30s")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_TIMEOUT=%q\n' "$val" >> "$tmp"
                val="$(_queue_mgr_prompt "Default kill-after, e.g. 5s")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_KILL_AFTER=%q\n' "$val" >> "$tmp"
                val="$(_queue_mgr_prompt "Default billing unit seconds")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_BILLING_UNIT_SECONDS=%q\n' "$val" >> "$tmp"
                val="$(_queue_mgr_prompt "Default billing cycles")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_BILLING_CYCLES=%q\n' "$val" >> "$tmp"
                val="$(_queue_mgr_prompt "Default billing grace seconds")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_BILLING_GRACE_SECONDS=%q\n' "$val" >> "$tmp"
                val="$(_queue_mgr_prompt "Default billing policy" "shortest-cap-wins")"; [[ -n "$val" ]] && printf 'CLASS_DEFAULT_BILLING_POLICY=%q\n' "$val" >> "$tmp"
                ;;
            2|3)
                mode="shared"
                [[ "$choice" == "3" ]] && mode="exclusive"

                mapfile -t facilities < <(_queue_mgr_list_facilities_compact)
                menu_items=()
                for facility in "${facilities[@]}"; do
                    menu_items+=("${facility//$'\t'/  -  }")
                done

                facility="$(_queue_mgr_tui_pick "Select asset facility for $mode check" "${menu_items[@]}")" || continue
                facility="${facility%%  -  *}"

                echo
                echo "Selected: $facility"
                echo "-----------------------------------------------------------------------------"
                queue asset-hint "$facility" 2>/dev/null || queue assets explain "$facility" 2>/dev/null || true
                echo "-----------------------------------------------------------------------------"

                family="$(_queue_mgr_facility_family "$facility")"
                check="$(_queue_mgr_facility_check "$facility")"

                target="$(_queue_mgr_prompt "Target for $facility")"
                [[ -n "$target" ]] || { echo "No target supplied; skipped."; continue; }

                params="$(_queue_mgr_prompt "Params as key=value pairs, space separated")"

                if [[ "$mode" == "shared" ]]; then
                    record="queue_class_shared_asset $(_queue_mgr_quote "$family") $(_queue_mgr_quote "$check") $(_queue_mgr_quote "$target")"
                else
                    record="queue_class_exclusive_asset $(_queue_mgr_quote "$family") $(_queue_mgr_quote "$check") $(_queue_mgr_quote "$target")"
                fi

                if [[ -n "$params" ]]; then
                    # Parameters are expected already as shell words. Keep this
                    # explicit so generated class files remain readable.
                    record+=" $params"
                fi

                records+=("$record")
                echo "Added: $record"
                ;;
            4)
                target="$(_queue_mgr_prompt "Exclusive claim token, e.g. github_publish:slot")"
                [[ -n "$target" ]] || continue
                record="queue_class_exclusive_claim $(_queue_mgr_quote "$target")"
                records+=("$record")
                echo "Added: $record"
                ;;
            5)
                _queue_mgr_wizard_render_preview "$class" "$allow_parallel" "$max_concurrent" "$tmp" "${records[@]}"
                _queue_mgr_pause
                ;;
            6)
                mkdir -p "$(_queue_root)/classes"
                local outfile="$(_queue_root)/classes/${class}.env"
                if [[ -f "$outfile" ]]; then
                    if [[ "$(_queue_mgr_prompt "Class exists. Replace? y/N" "N")" != [Yy]* ]]; then
                        continue
                    fi
                    mkdir -p "$(_queue_root)/classes/.backup"
                    cp "$outfile" "$(_queue_root)/classes/.backup/${class}.$(date +%Y%m%d_%H%M%S_%N).env"
                fi

                _queue_mgr_wizard_render_preview "$class" "$allow_parallel" "$max_concurrent" "$tmp" "${records[@]}" > "$outfile"

                if queue classes validate "$class"; then
                    echo "Saved class: $outfile"
                    return 0
                else
                    echo "Saved class failed validation: $outfile" >&2
                    return 1
                fi
                ;;
            7|q|Q)
                return 1
                ;;
            *)
                echo "Unknown selection: $choice"
                ;;
        esac
    done
}


_queue_mgr_panel() {
    local here script
    script="${QUEUEBASH_PANEL_MANAGER:-}"
    if [[ -z "$script" ]]; then
        here="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"
        script="$here/queuemgr_panel.py"
    fi
    [[ -f "$script" ]] || { echo "QueueManager panel script not found: $script" >&2; return 1; }
    export QUEUEBASH_SOURCE="${QUEUEBASH_SOURCE:-$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)/queuebash.sh}"
    python3 "$script"
}
