#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
fail(){ echo "[FAIL] $*" >&2; exit 1; }
[[ -f docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md ]] || fail 'maintenance evidence contract doc missing'
[[ -x providers.d/enterprise/maintenance_evidence_verify.sh ]] || fail 'maintenance evidence verifier missing or not executable'
[[ -f schemas/enterprise/approved_maintenance_request.example.json ]] || fail 'request schema example missing'
[[ -f schemas/enterprise/approved_maintenance_decision.allowed.example.json ]] || fail 'allowed decision schema example missing'
[[ -f schemas/enterprise/approved_maintenance_decision.blocked.example.json ]] || fail 'blocked decision schema example missing'
[[ -f schemas/enterprise/approved_maintenance_cluster_context.example.json ]] || fail 'cluster context schema example missing'
grep -q 'queuebash.enterprise_maintenance_evidence_request.v1' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing request schema'
grep -q 'queuebash.enterprise_maintenance_evidence_decision.v1' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing decision schema'
grep -q 'live_clearance_granted: false' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc must deny broad live clearance'
grep -q 'secret_env_allowed = false' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing secret env denial'
grep -q '/etc/queuebash/policies.d' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing canonical policy root'
grep -q 'does not execute commands' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing no execution boundary'
grep -q 'evidence_hash' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing evidence hash contract'
grep -q 'queuebash.enterprise_maintenance_cluster_context.v1' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster context schema'
grep -q 'cluster_leader_lease_must_cover_window' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster lease/window failure'
grep -q 'cluster_quorum_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster quorum check'
grep -q 'cluster_node_targets_must_be_explicit' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing explicit node target check'
grep -q 'cluster_fixture_must_not_touch_network' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster fixture no-network boundary'
grep -q 'cluster_membership_hash_required' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster membership hash failure'
grep -q 'cluster_fence_token_must_be_redacted' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster fence redaction failure'
grep -q 'cluster_split_brain_guard_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing split-brain guard check'
grep -q 'cluster_vote_nodes_below_quorum' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing vote node quorum check'
grep -q 'cluster_fence_token_hash_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing fence token hash check'
grep -q 'cluster_blast_radius_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster blast-radius check'
grep -q 'cluster_canary_completion_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster canary completion check'
grep -q 'cluster_drain_verified_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster drain verification check'
grep -q 'cluster_rollback_checkpoint_must_be_redacted' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster rollback redaction check'
grep -q 'cluster_blast_radius_percentage_limited' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster blast-radius percentage failure'
grep -q 'cluster_canary_health_ok_required' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster canary health failure'
grep -q 'cluster_rollback_checkpoint_hash_required' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster rollback checkpoint hash failure'
grep -q 'cluster_observation_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster observation requirement'
grep -q 'cluster_observation_health_ok_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster observation health check'
grep -q 'cluster_observation_error_budget_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster observation SLO budget check'
grep -q 'cluster_observation_raw_evidence_must_be_redacted' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster observation redaction check'
grep -q 'cluster_observation_error_rate_regression_denied' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster observation error-rate failure'
grep -q 'cluster_abort_criteria_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster abort criteria check'
grep -q 'cluster_abort_policy_must_be_redacted' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster abort redaction check'
grep -q 'cluster_incident_response_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster incident response check'
grep -q 'cluster_incident_contacts_must_be_redacted' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster incident contact redaction check'
grep -q 'cluster.abort_criteria.policy_hash' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster abort policy hash contract'
grep -q 'cluster.incident_response.comms_channel_hash' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster incident comms hash contract'

grep -q 'cluster_evidence_bundle_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster evidence bundle requirement'
grep -q 'cluster_evidence_bundle_hash_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster evidence bundle hash check'
grep -q 'cluster_evidence_bundle_signature_verified_required' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster evidence bundle signature verification check'
grep -q 'cluster_evidence_bundle_raw_material_must_be_redacted' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing cluster evidence bundle redaction check'
grep -q 'cluster.evidence_bundle.bundle_hash' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster evidence bundle hash contract'
grep -q 'cluster.evidence_bundle.retention_days >= 90' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster evidence bundle retention contract'
grep -q 'cluster.observation.evidence_hash' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing cluster observation evidence hash contract'
grep -q 'requester_hash' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing requester redaction contract'
grep -q 'approvers must not include requester' docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md || fail 'doc missing approver independence rule'
grep -q 'evidence_must_not_expire_before_window_end' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing expiry/window check'
grep -q 'requester_must_not_approve_own_maintenance' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing requester self-approval guard'
grep -q 'redacted' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing redaction marker'
grep -q 'secret_value_included' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier missing secret value exclusion marker'
grep -q 'system_modified.*False' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier must report system_modified false'
grep -q 'live_clearance_granted.*False' providers.d/enterprise/maintenance_evidence_verify.sh || fail 'verifier must report live_clearance_granted false'
! grep -R "secret_value[[:space:]]*[:=]" docs/APPROVED_MAINTENANCE_EVIDENCE_CONTRACT.md schemas/enterprise/approved_maintenance_*.json tests/fixtures/enterprise/maintenance_evidence providers.d/enterprise/maintenance_evidence_verify.sh >/tmp/qb_maint_secret_grep.$$ || { cat /tmp/qb_maint_secret_grep.$$ >&2; rm -f /tmp/qb_maint_secret_grep.$$; fail 'raw secret_value field detected'; }
rm -f /tmp/qb_maint_secret_grep.$$
echo '[PASS] enterprise_maintenance_evidence_static'
