#!/usr/bin/env bash
set -euo pipefail
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
panel="$repo_root/queuemgr_panel.py"
qdoc="$repo_root/docs/QUEUEMGR.md"
readme="$repo_root/README.md"
changelog="$repo_root/CHANGELOG.md"
fail(){ echo "[FAIL] $*" >&2; exit 1; }
python3 -m py_compile "$panel" || fail "queuemgr_panel.py does not compile"
grep -q 'class AskDraft' "$panel" || fail "AskDraft missing"
grep -q 'def discover_ai_ask_providers' "$panel" || fail "provider discovery missing"
grep -q 'ViewState("ask", "Ask", load_ask, detail_ask)' "$panel" || fail "Ask view missing"
grep -q '"ask": "I"' "$panel" || fail "Ask hotkey missing"
grep -q 'def execute_ask_command' "$panel" || fail "Ask command handler missing"
grep -q 'def run_ask_request' "$panel" || fail "Ask runner missing"
grep -q 'qrun(args, timeout=240, dry_run=self.dry_run)' "$panel" || fail "Ask panel does not use existing qrun/queue ask path"
grep -q 'queue ask --help' "$panel" || fail "Ask panel does not inspect queue ask provider help"
grep -q 'name in {"name", "provider", "model"}' "$panel" || fail "Ask provider discovery should skip usage placeholders"
grep -q 'queue-ai-ask-gemini' "$panel" || fail "Gemini helper discovery missing"
grep -q 'queue-ai-ask-ollama' "$panel" || fail "Ollama helper discovery missing"
grep -q 'examples.*providers.*ai' "$panel" || fail "AI provider example discovery missing"
grep -q 'Advisory only' "$panel" || fail "Ask panel advisory-only warning missing"
grep -q 'Ask panel' "$qdoc" || fail "QueueManager docs missing Ask panel section"
grep -q 'ask provider gemini' "$qdoc" || fail "QueueManager docs missing Ask examples"
grep -q 'Queue Manager Ask panel add-on' "$readme" || fail "README missing Ask panel release note"
grep -q 'Queue Manager Ask panel add-on' "$changelog" || fail "CHANGELOG missing Ask panel release note"
grep -q 'QUEUEBASH_VERSION="0.18.31"' "$repo_root/queuebash.sh" || fail "queuebash.sh version should remain on 0.18.31 for panel-only sidestep"
echo "[PASS] Queue Manager Ask panel static checks"
