#!/usr/bin/env bash
# bashqueues asset plugin: fileprofile
# Verifies approved/signed file/resource profiles generated by interrogation mode.

queue_asset_facilities() {
    cat <<'FACILITIES'
fileprofile:profile_exists	Blocks dispatch unless an approved file/resource profile exists
fileprofile:profile_signed	Blocks dispatch unless an approved file/resource profile is signed
fileprofile:profile_verified	Blocks dispatch unless the approved profile signature matches its content
FACILITIES
}

queue_asset_hints() {
    cat <<'EOF_HINTS'
fileprofile:profile_exists	target=profile name	params=profile_file=/path profile_root=/path	example=queue_class_shared_asset fileprofile profile_exists wget_google	notes=Finds approved interrogation file/resource profiles.
fileprofile:profile_signed	target=profile name	params=profile_file=/path profile_root=/path	example=queue_class_shared_asset fileprofile profile_signed wget_google	notes=Requires SHOULD_BE_SIGNED=1, STATUS=approved, SIGNED=1.
fileprofile:profile_verified	target=profile name	params=profile_file=/path profile_root=/path allow_self_signed=1 required_signer=name[,name]	example=queue_class_shared_asset fileprofile profile_verified wget_google allow_self_signed=0 required_signer=ops-release	notes=Verifies the SHA256 stamp and signer trust policy over the approved profile content.
EOF_HINTS
}

queue_asset_param() { local key="$1" p; shift || true; for p in "$@"; do case "$p" in "$key="*) printf '%s\n' "${p#*=}"; return 0;; esac; done; return 1; }

_queue_asset_fileprofile_file() {
    local name="$1" profile_file profile_root qroot cand safe
    shift || true
    profile_file="$(queue_asset_param profile_file "$@" || true)"
    [[ -n "$profile_file" ]] && { printf '%s\n' "$profile_file"; return 0; }
    safe="$(printf '%s' "$name" | sed 's/[^A-Za-z0-9_.-]/_/g')"
    profile_root="$(queue_asset_param profile_root "$@" || true)"
    qroot="${QUEUEBASH_ROOT:-$HOME/.queuebash}"
    for cand in \
        "$profile_root/approved/$safe.file.env" \
        "$qroot/profiles/interrogation/approved/$safe.file.env" \
        "/etc/bashqueues/interrogation/approved/$safe.file.env"; do
        [[ -n "$cand" && -f "$cand" ]] && { printf '%s\n' "$cand"; return 0; }
    done
    return 1
}

_queue_asset_fileprofile_get() { grep -E "^$2=" "$1" 2>/dev/null | tail -n1 | cut -d= -f2-; }
_queue_asset_fileprofile_sig_content() { grep -Ev '^FILEPROFILE_SIGNATURE_SHA256=' "$1" 2>/dev/null; }
_queue_asset_fileprofile_hash() { _queue_asset_fileprofile_sig_content "$1" | sha256sum | awk '{print $1}'; }
_queue_asset_fileprofile_csv_has() {
    local needle="$1" list="$2" x
    IFS=',' read -r -a _queue_asset_fileprofile_items <<< "$list"
    for x in "${_queue_asset_fileprofile_items[@]}"; do
        x="${x//[[:space:]]/}"
        [[ "$x" == "$needle" ]] && return 0
    done
    return 1
}
_queue_asset_fileprofile_trust_ok() {
    local file="$1" shift_dummy="${2:-}"; shift || true
    local allow_self required signed_by self_signed
    allow_self="$(queue_asset_param allow_self_signed "$@" || echo 1)"
    required="$(queue_asset_param required_signer "$@" || true)"
    signed_by="$(_queue_asset_fileprofile_get "$file" FILEPROFILE_SIGNED_BY)"
    self_signed="$(_queue_asset_fileprofile_get "$file" FILEPROFILE_SELF_SIGNED)"
    if [[ -n "$required" ]] && ! _queue_asset_fileprofile_csv_has "$signed_by" "$required"; then
        echo "asset_check_blocked: fileprofile:profile_verified signer_not_required signed_by=${signed_by:-unknown} required=$required"
        return 1
    fi
    case "$allow_self" in 0|no|false|off)
        if [[ "$self_signed" == "1" || "$signed_by" == self:* ]]; then
            echo "asset_check_blocked: fileprofile:profile_verified self_signed_not_allowed signed_by=${signed_by:-unknown}"
            return 1
        fi
        ;;
    esac
    return 0
}

queue_asset_check_fileprofile_profile_exists() {
    local token="$1" name="$2" f; shift 2 || true
    [[ -n "$name" ]] || { echo "asset_check_blocked: fileprofile:profile_exists profile_required"; return 1; }
    f="$(_queue_asset_fileprofile_file "$name" "$@" 2>/dev/null || true)"
    [[ -r "$f" ]] || { echo "asset_check_blocked: fileprofile:profile_exists missing name=$name"; return 1; }
    echo "asset_check_ok: fileprofile:profile_exists name=$name file=$f"
}

queue_asset_check_fileprofile_profile_signed() {
    local token="$1" name="$2" f status should signed; shift 2 || true
    f="$(_queue_asset_fileprofile_file "$name" "$@" 2>/dev/null || true)"
    [[ -r "$f" ]] || { echo "asset_check_blocked: fileprofile:profile_signed missing name=$name"; return 1; }
    status="$(_queue_asset_fileprofile_get "$f" FILEPROFILE_STATUS)"
    should="$(_queue_asset_fileprofile_get "$f" FILEPROFILE_SHOULD_BE_SIGNED)"
    signed="$(_queue_asset_fileprofile_get "$f" FILEPROFILE_SIGNED)"
    [[ "$status" == "approved" && "$should" == "1" && "$signed" == "1" ]] || { echo "asset_check_blocked: fileprofile:profile_signed unsigned_or_candidate name=$name status=$status signed=$signed"; return 1; }
    echo "asset_check_ok: fileprofile:profile_signed name=$name"
}

queue_asset_check_fileprofile_profile_verified() {
    local token="$1" name="$2" f expected actual signed_by; shift 2 || true
    queue_asset_check_fileprofile_profile_signed "$token" "$name" "$@" >/dev/null || return 1
    f="$(_queue_asset_fileprofile_file "$name" "$@" 2>/dev/null || true)"
    expected="$(_queue_asset_fileprofile_get "$f" FILEPROFILE_SIGNATURE_SHA256)"
    actual="$(_queue_asset_fileprofile_hash "$f")"
    [[ -n "$expected" && "$expected" == "$actual" ]] || { echo "asset_check_blocked: fileprofile:profile_verified signature_mismatch name=$name"; return 1; }
    _queue_asset_fileprofile_trust_ok "$f" _ "$@" || return 1
    signed_by="$(_queue_asset_fileprofile_get "$f" FILEPROFILE_SIGNED_BY)"
    echo "asset_check_ok: fileprofile:profile_verified name=$name signed_by=${signed_by:-unknown}"
}
