#!/usr/bin/env bash
# bashqueues asset plugin: netprofile
# Verifies approved/signed network/port profiles generated by interrogation mode.

queue_asset_facilities() {
    cat <<'FACILITIES'
netprofile:profile_exists	Blocks dispatch unless an approved network/port profile exists
netprofile:profile_signed	Blocks dispatch unless an approved network/port profile is signed
netprofile:profile_verified	Blocks dispatch unless the approved profile signature matches its content
FACILITIES
}

queue_asset_hints() {
    cat <<'EOF_HINTS'
netprofile:profile_exists	target=profile name	params=profile_file=/path profile_root=/path	example=queue_class_shared_asset netprofile profile_exists wget_google	notes=Finds approved interrogation network/port profiles.
netprofile:profile_signed	target=profile name	params=profile_file=/path profile_root=/path	example=queue_class_shared_asset netprofile profile_signed wget_google	notes=Requires SHOULD_BE_SIGNED=1, STATUS=approved, SIGNED=1.
netprofile:profile_verified	target=profile name	params=profile_file=/path profile_root=/path	example=queue_class_shared_asset netprofile profile_verified wget_google	notes=Verifies the SHA256 stamp over the approved profile content.
EOF_HINTS
}

queue_asset_param() { local key="$1" p; shift || true; for p in "$@"; do case "$p" in "$key="*) printf '%s\n' "${p#*=}"; return 0;; esac; done; return 1; }

_queue_asset_netprofile_file() {
    local name="$1" profile_file profile_root qroot cand safe
    shift || true
    profile_file="$(queue_asset_param profile_file "$@" || true)"
    [[ -n "$profile_file" ]] && { printf '%s\n' "$profile_file"; return 0; }
    safe="$(printf '%s' "$name" | sed 's/[^A-Za-z0-9_.-]/_/g')"
    profile_root="$(queue_asset_param profile_root "$@" || true)"
    qroot="${QUEUEBASH_ROOT:-$HOME/.queuebash}"
    for cand in \
        "$profile_root/approved/$safe.net.env" \
        "$qroot/profiles/interrogation/approved/$safe.net.env" \
        "/etc/bashqueues/interrogation/approved/$safe.net.env"; do
        [[ -n "$cand" && -f "$cand" ]] && { printf '%s\n' "$cand"; return 0; }
    done
    return 1
}

_queue_asset_netprofile_get() { grep -E "^$2=" "$1" 2>/dev/null | tail -n1 | cut -d= -f2-; }
_queue_asset_netprofile_sig_content() { grep -Ev '^NETPROFILE_SIGNATURE_SHA256=' "$1" 2>/dev/null; }
_queue_asset_netprofile_hash() { _queue_asset_netprofile_sig_content "$1" | sha256sum | awk '{print $1}'; }

queue_asset_check_netprofile_profile_exists() {
    local token="$1" name="$2" f; shift 2 || true
    [[ -n "$name" ]] || { echo "asset_check_blocked: netprofile:profile_exists profile_required"; return 1; }
    f="$(_queue_asset_netprofile_file "$name" "$@" 2>/dev/null || true)"
    [[ -r "$f" ]] || { echo "asset_check_blocked: netprofile:profile_exists missing name=$name"; return 1; }
    echo "asset_check_ok: netprofile:profile_exists name=$name file=$f"
}

queue_asset_check_netprofile_profile_signed() {
    local token="$1" name="$2" f status should signed; shift 2 || true
    f="$(_queue_asset_netprofile_file "$name" "$@" 2>/dev/null || true)"
    [[ -r "$f" ]] || { echo "asset_check_blocked: netprofile:profile_signed missing name=$name"; return 1; }
    status="$(_queue_asset_netprofile_get "$f" NETPROFILE_STATUS)"
    should="$(_queue_asset_netprofile_get "$f" NETPROFILE_SHOULD_BE_SIGNED)"
    signed="$(_queue_asset_netprofile_get "$f" NETPROFILE_SIGNED)"
    [[ "$status" == "approved" && "$should" == "1" && "$signed" == "1" ]] || { echo "asset_check_blocked: netprofile:profile_signed unsigned_or_candidate name=$name status=$status signed=$signed"; return 1; }
    echo "asset_check_ok: netprofile:profile_signed name=$name"
}

queue_asset_check_netprofile_profile_verified() {
    local token="$1" name="$2" f expected actual; shift 2 || true
    queue_asset_check_netprofile_profile_signed "$token" "$name" "$@" >/dev/null || return 1
    f="$(_queue_asset_netprofile_file "$name" "$@" 2>/dev/null || true)"
    expected="$(_queue_asset_netprofile_get "$f" NETPROFILE_SIGNATURE_SHA256)"
    actual="$(_queue_asset_netprofile_hash "$f")"
    [[ -n "$expected" && "$expected" == "$actual" ]] || { echo "asset_check_blocked: netprofile:profile_verified signature_mismatch name=$name"; return 1; }
    echo "asset_check_ok: netprofile:profile_verified name=$name"
}
