#!/usr/bin/env bash
# bashqueues asset plugin: netprofile
# Verifies approved/signed network/port profiles generated by interrogation mode.

queue_asset_facilities() {
    cat <<'FACILITIES'
netprofile:profile_exists	Blocks dispatch unless an approved network/port profile exists
netprofile:profile_signed	Blocks dispatch unless an approved network/port profile is signed
netprofile:profile_verified	Blocks dispatch unless the approved profile signature matches its content
FACILITIES
}

queue_asset_hints() {
    cat <<'EOF_HINTS'
netprofile:profile_exists	target=profile name	params=profile_file=/path profile_root=/path	example=queue_class_shared_asset netprofile profile_exists wget_google	notes=Finds approved interrogation network/port profiles.
netprofile:profile_signed	target=profile name	params=profile_file=/path profile_root=/path	example=queue_class_shared_asset netprofile profile_signed wget_google	notes=Requires SHOULD_BE_SIGNED=1, STATUS=approved, SIGNED=1.
netprofile:profile_verified	target=profile name	params=profile_file=/path profile_root=/path allow_self_signed=1 required_signer=name[,name]	example=queue_class_shared_asset netprofile profile_verified wget_google allow_self_signed=0 required_signer=ops-release	notes=Verifies the SHA256 payload stamp, optional Ed25519 signature, and signer trust policy over the approved profile content.
EOF_HINTS
}

queue_asset_param() { local key="$1" p; shift || true; for p in "$@"; do case "$p" in "$key="*) printf '%s\n' "${p#*=}"; return 0;; esac; done; return 1; }

_queue_asset_netprofile_file() {
    local name="$1" profile_file profile_root qroot cand safe
    shift || true
    profile_file="$(queue_asset_param profile_file "$@" || true)"
    [[ -n "$profile_file" ]] && { printf '%s\n' "$profile_file"; return 0; }
    safe="$(printf '%s' "$name" | sed 's/[^A-Za-z0-9_.-]/_/g')"
    profile_root="$(queue_asset_param profile_root "$@" || true)"
    qroot="${QUEUEBASH_ROOT:-$HOME/.queuebash}"
    for cand in \
        "$profile_root/approved/$safe.net.env" \
        "$qroot/profiles/interrogation/approved/$safe.net.env" \
        "/etc/bashqueues/interrogation/approved/$safe.net.env"; do
        [[ -n "$cand" && -f "$cand" ]] && { printf '%s\n' "$cand"; return 0; }
    done
    return 1
}

_queue_asset_netprofile_get() { grep -E "^$2=" "$1" 2>/dev/null | tail -n1 | cut -d= -f2-; }
_queue_asset_netprofile_sig_content() { grep -Ev '^NETPROFILE_(SIGNATURE_SHA256|SIGNATURE_PAYLOAD_SHA256|SIGNATURE_B64|SIGNATURE_ALG|PUBLIC_KEY_SHA256)=' "$1" 2>/dev/null; }
_queue_asset_netprofile_hash() { _queue_asset_netprofile_sig_content "$1" | sha256sum | awk '{print $1}'; }
_queue_asset_netprofile_csv_has() {
    local needle="$1" list="$2" x
    IFS=',' read -r -a _queue_asset_netprofile_items <<< "$list"
    for x in "${_queue_asset_netprofile_items[@]}"; do
        x="${x//[[:space:]]/}"
        [[ "$x" == "$needle" ]] && return 0
    done
    return 1
}

_queue_asset_netprofile_key_root() {
    if [[ -n "${QUEUEBASH_PROFILE_KEY_ROOT:-}" ]]; then printf '%s
' "${QUEUEBASH_PROFILE_KEY_ROOT%/}"; return 0; fi
    if [[ -n "${QUEUEBASH_AUTHORISATION_KEY_ROOT:-}" ]]; then printf '%s
' "${QUEUEBASH_AUTHORISATION_KEY_ROOT%/}"; return 0; fi
    printf '%s/keys
' "${QUEUEBASH_ROOT:-$HOME/.queuebash}"
}
_queue_asset_netprofile_public_key() { printf '%s/public/%s.ed25519.pub.pem
' "$(_queue_asset_netprofile_key_root)" "$1"; }
_queue_asset_netprofile_file_sha256() { sha256sum "$1" 2>/dev/null | awk '{print $1}'; }
_queue_asset_netprofile_verify_ed25519() {
    local file="$1" signed_by sig_b64 pub expected_pub_sha actual_pub_sha tmpdir payload sigfile rc alg
    alg="$(_queue_asset_netprofile_get "$file" NETPROFILE_SIGNATURE_ALG)"
    sig_b64="$(_queue_asset_netprofile_get "$file" NETPROFILE_SIGNATURE_B64)"
    [[ -n "$sig_b64" ]] || return 0
    [[ "$alg" == "ed25519" ]] || { echo "asset_check_blocked: netprofile:profile_verified unsupported_signature_alg alg=${alg:-unknown}"; return 1; }
    command -v openssl >/dev/null 2>&1 || { echo "asset_check_blocked: netprofile:profile_verified openssl_required"; return 1; }
    command -v base64 >/dev/null 2>&1 || { echo "asset_check_blocked: netprofile:profile_verified base64_required"; return 1; }
    signed_by="$(_queue_asset_netprofile_get "$file" NETPROFILE_SIGNED_BY)"
    pub="$(_queue_asset_netprofile_public_key "$signed_by")"
    [[ -r "$pub" ]] || { echo "asset_check_blocked: netprofile:profile_verified public_key_missing signer=${signed_by:-unknown} path=$pub"; return 1; }
    expected_pub_sha="$(_queue_asset_netprofile_get "$file" NETPROFILE_PUBLIC_KEY_SHA256)"
    actual_pub_sha="$(_queue_asset_netprofile_file_sha256 "$pub")"
    if [[ -n "$expected_pub_sha" && -n "$actual_pub_sha" && "$expected_pub_sha" != "$actual_pub_sha" ]]; then
        echo "asset_check_blocked: netprofile:profile_verified public_key_sha_mismatch signer=${signed_by:-unknown}"
        return 1
    fi
    tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/queue-netprofile-verify.XXXXXX")" || return 1
    payload="$tmpdir/payload"; sigfile="$tmpdir/sig.bin"
    _queue_asset_netprofile_sig_content "$file" > "$payload"
    printf '%s' "$sig_b64" | base64 -d > "$sigfile" 2>/dev/null || { rm -rf "$tmpdir"; echo "asset_check_blocked: netprofile:profile_verified signature_b64_invalid"; return 1; }
    if openssl pkeyutl -verify -rawin -pubin -inkey "$pub" -sigfile "$sigfile" -in "$payload" >/dev/null 2>&1; then
        rm -rf "$tmpdir"; return 0
    fi
    rc=$?; rm -rf "$tmpdir"
    echo "asset_check_blocked: netprofile:profile_verified ed25519_signature_invalid signer=${signed_by:-unknown}"
    return "$rc"
}

_queue_asset_netprofile_trust_ok() {
    local file="$1" shift_dummy="${2:-}"; shift || true
    local allow_self required signed_by self_signed
    allow_self="$(queue_asset_param allow_self_signed "$@" || echo 1)"
    required="$(queue_asset_param required_signer "$@" || true)"
    signed_by="$(_queue_asset_netprofile_get "$file" NETPROFILE_SIGNED_BY)"
    self_signed="$(_queue_asset_netprofile_get "$file" NETPROFILE_SELF_SIGNED)"
    if [[ -n "$required" ]] && ! _queue_asset_netprofile_csv_has "$signed_by" "$required"; then
        echo "asset_check_blocked: netprofile:profile_verified signer_not_required signed_by=${signed_by:-unknown} required=$required"
        return 1
    fi
    case "$allow_self" in 0|no|false|off)
        if [[ "$self_signed" == "1" || "$signed_by" == self:* ]]; then
            echo "asset_check_blocked: netprofile:profile_verified self_signed_not_allowed signed_by=${signed_by:-unknown}"
            return 1
        fi
        ;;
    esac
    return 0
}

queue_asset_check_netprofile_profile_exists() {
    local token="$1" name="$2" f; shift 2 || true
    [[ -n "$name" ]] || { echo "asset_check_blocked: netprofile:profile_exists profile_required"; return 1; }
    f="$(_queue_asset_netprofile_file "$name" "$@" 2>/dev/null || true)"
    [[ -r "$f" ]] || { echo "asset_check_blocked: netprofile:profile_exists missing name=$name"; return 1; }
    echo "asset_check_ok: netprofile:profile_exists name=$name file=$f"
}

queue_asset_check_netprofile_profile_signed() {
    local token="$1" name="$2" f status should signed; shift 2 || true
    f="$(_queue_asset_netprofile_file "$name" "$@" 2>/dev/null || true)"
    [[ -r "$f" ]] || { echo "asset_check_blocked: netprofile:profile_signed missing name=$name"; return 1; }
    status="$(_queue_asset_netprofile_get "$f" NETPROFILE_STATUS)"
    should="$(_queue_asset_netprofile_get "$f" NETPROFILE_SHOULD_BE_SIGNED)"
    signed="$(_queue_asset_netprofile_get "$f" NETPROFILE_SIGNED)"
    [[ "$status" == "approved" && "$should" == "1" && "$signed" == "1" ]] || { echo "asset_check_blocked: netprofile:profile_signed unsigned_or_candidate name=$name status=$status signed=$signed"; return 1; }
    echo "asset_check_ok: netprofile:profile_signed name=$name"
}

queue_asset_check_netprofile_profile_verified() {
    local token="$1" name="$2" f expected actual signed_by; shift 2 || true
    queue_asset_check_netprofile_profile_signed "$token" "$name" "$@" >/dev/null || return 1
    f="$(_queue_asset_netprofile_file "$name" "$@" 2>/dev/null || true)"
    expected="$(_queue_asset_netprofile_get "$f" NETPROFILE_SIGNATURE_SHA256)"
    actual="$(_queue_asset_netprofile_hash "$f")"
    [[ -n "$expected" && "$expected" == "$actual" ]] || { echo "asset_check_blocked: netprofile:profile_verified signature_mismatch name=$name"; return 1; }
    _queue_asset_netprofile_verify_ed25519 "$f" || return 1
    _queue_asset_netprofile_trust_ok "$f" _ "$@" || return 1
    signed_by="$(_queue_asset_netprofile_get "$f" NETPROFILE_SIGNED_BY)"
    echo "asset_check_ok: netprofile:profile_verified name=$name signed_by=${signed_by:-unknown}"
}
