#!/usr/bin/env bash
# bashqueues asset plugin: secprofile
# Verifies approved/signed syscall profiles generated by interrogation mode.

queue_asset_facilities() {
    cat <<'FACILITIES'
secprofile:profile_exists	Blocks dispatch unless an approved seccomp/syscall profile exists
secprofile:profile_signed	Blocks dispatch unless an approved seccomp/syscall profile is signed
secprofile:profile_verified	Blocks dispatch unless the approved profile signature matches its content
FACILITIES
}

queue_asset_hints() {
    cat <<'EOF_HINTS'
secprofile:profile_exists	target=profile name	params=profile_file=/path profile_root=/path	example=queue_class_shared_asset secprofile profile_exists wget_google	notes=Finds approved interrogation seccomp profiles.
secprofile:profile_signed	target=profile name	params=profile_file=/path profile_root=/path	example=queue_class_shared_asset secprofile profile_signed wget_google	notes=Requires SHOULD_BE_SIGNED=1, STATUS=approved, SIGNED=1.
secprofile:profile_verified	target=profile name	params=profile_file=/path profile_root=/path	example=queue_class_shared_asset secprofile profile_verified wget_google	notes=Verifies the SHA256 stamp over the approved profile content.
EOF_HINTS
}

queue_asset_param() { local key="$1" p; shift || true; for p in "$@"; do case "$p" in "$key="*) printf '%s\n' "${p#*=}"; return 0;; esac; done; return 1; }

_queue_asset_secprofile_file() {
    local name="$1" profile_file profile_root qroot cand safe
    shift || true
    profile_file="$(queue_asset_param profile_file "$@" || true)"
    [[ -n "$profile_file" ]] && { printf '%s\n' "$profile_file"; return 0; }
    safe="$(printf '%s' "$name" | sed 's/[^A-Za-z0-9_.-]/_/g')"
    profile_root="$(queue_asset_param profile_root "$@" || true)"
    qroot="${QUEUEBASH_ROOT:-$HOME/.queuebash}"
    for cand in \
        "$profile_root/approved/$safe.seccomp.env" \
        "$qroot/profiles/interrogation/approved/$safe.seccomp.env" \
        "/etc/bashqueues/interrogation/approved/$safe.seccomp.env"; do
        [[ -n "$cand" && -f "$cand" ]] && { printf '%s\n' "$cand"; return 0; }
    done
    return 1
}

_queue_asset_secprofile_get() { grep -E "^$2=" "$1" 2>/dev/null | tail -n1 | cut -d= -f2-; }
_queue_asset_secprofile_sig_content() { grep -Ev '^SECPROFILE_SIGNATURE_SHA256=' "$1" 2>/dev/null; }
_queue_asset_secprofile_hash() { _queue_asset_secprofile_sig_content "$1" | sha256sum | awk '{print $1}'; }

queue_asset_check_secprofile_profile_exists() {
    local token="$1" name="$2" f; shift 2 || true
    [[ -n "$name" ]] || { echo "asset_check_blocked: secprofile:profile_exists profile_required"; return 1; }
    f="$(_queue_asset_secprofile_file "$name" "$@" 2>/dev/null || true)"
    [[ -r "$f" ]] || { echo "asset_check_blocked: secprofile:profile_exists missing name=$name"; return 1; }
    echo "asset_check_ok: secprofile:profile_exists name=$name file=$f"
}

queue_asset_check_secprofile_profile_signed() {
    local token="$1" name="$2" f status should signed; shift 2 || true
    f="$(_queue_asset_secprofile_file "$name" "$@" 2>/dev/null || true)"
    [[ -r "$f" ]] || { echo "asset_check_blocked: secprofile:profile_signed missing name=$name"; return 1; }
    status="$(_queue_asset_secprofile_get "$f" SECPROFILE_STATUS)"
    should="$(_queue_asset_secprofile_get "$f" SECPROFILE_SHOULD_BE_SIGNED)"
    signed="$(_queue_asset_secprofile_get "$f" SECPROFILE_SIGNED)"
    [[ "$status" == "approved" && "$should" == "1" && "$signed" == "1" ]] || { echo "asset_check_blocked: secprofile:profile_signed unsigned_or_candidate name=$name status=$status signed=$signed"; return 1; }
    echo "asset_check_ok: secprofile:profile_signed name=$name"
}

queue_asset_check_secprofile_profile_verified() {
    local token="$1" name="$2" f expected actual; shift 2 || true
    queue_asset_check_secprofile_profile_signed "$token" "$name" "$@" >/dev/null || return 1
    f="$(_queue_asset_secprofile_file "$name" "$@" 2>/dev/null || true)"
    expected="$(_queue_asset_secprofile_get "$f" SECPROFILE_SIGNATURE_SHA256)"
    actual="$(_queue_asset_secprofile_hash "$f")"
    [[ -n "$expected" && "$expected" == "$actual" ]] || { echo "asset_check_blocked: secprofile:profile_verified signature_mismatch name=$name"; return 1; }
    echo "asset_check_ok: secprofile:profile_verified name=$name"
}
